version: '3.8'
services:
  appseed-app:
    container_name: appseed_app
    restart: always
    build: .
    networks:
      - db_network
      - web_network
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "5085:5085"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - appseed-app
  grafana: 
    container_name: grafana
    restart: always
    image: "grafana/grafana:latest"
    ports:
      - "3001:3000
    volumes:
      - grafana:/var/lib/grafana
    networks:
      - web_network

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
 
volumes:
  grafana: